# stage 0: build react
FROM node:10.15-alpine

WORKDIR /client

COPY package.json .

RUN apk add yarn && yarn install

COPY public public
COPY src src

RUN yarn build

# stage 1: serve with nginx
FROM nginx:1.17-alpine

COPY --from=0 /client/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
