version: "2"

services:
  db:
    image: mongo:4.0-xenial
    volumes:
      - data:/data/db
  server:
    build: server
    depends_on:
      - db
  client:
    build: client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  data:
