version: "2.4"

services:
  mongo:
    image: mongo:4.0-xenial
    volumes:
      - data:/data/db
  flask:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  nginx:
    build: ./client
    ports:
      - "5000:80"
    depends_on:
      - flask

volumes:
  data:
