version: "2"

services:
  mongo:
    image: mongo:4.0-xenial
    volumes:
      - data:/data/db
  flask:
    build: ./server
    depends_on:
      - mongo
  nginx:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - flask

volumes:
  data:
